spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/database
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# JWT Configuration
jwt.secret=your-super-secret-key-change-this-in-production-min-256-bits
jwt.expiration=86400000
# 24 hours in milliseconds

# Security
spring.security.user.name=admin
spring.security.user.password=admin123

# App (for email links)
app.base-url=http://localhost:8080
app.mail.from=noreply@example.com

# PayPal (International)
paypal.client.id=YOUR_CLIENT_ID
paypal.client.secret=YOUR_CLIENT_SECRET
paypal.mode=sandbox

# SMT Monetique (Tunisie)
smt.merchant.id=YOUR_MERCHANT_ID
smt.terminal.id=YOUR_TERMINAL_ID
smt.api.key=YOUR_API_KEY
smt.api.url=https://www.monetique.com.tn/payment/api

# URLs de callback
app.payment.return.url=http://localhost:4200/payment-result
app.payment.cancel.url=http://localhost:4200/payment-result

# Flouci (Tunisie)
flouci.api.url=https://developers.flouci.com/api/v2
flouci.app.public=YOUR_FLOUCI_APP_PUBLIC
flouci.app.secret=YOUR_FLOUCI_APP_SECRET