spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/database
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# JWT Configuration
jwt.secret=your-super-secret-key-change-this-in-production-min-256-bits
jwt.expiration=86400000

spring.security.user.name=admin
spring.security.user.password=admin123

# App (for email links)
app.base-url=http://localhost:8080
app.frontend-url=http://localhost:4200
app.mail.from=globextunisia@gmail.com

# PayPal (International)
paypal.client.id=AW25JlCtdaH5ZgPKFC3ZWGg3KeRESVXtWbCgc6mkkSjgMGygl5NLOxlMzLsHtvEhCjdtv6RS_4uVCPjm
paypal.client.secret=EERHEkQdOhmoTa6iqlDlREZijEBM-adjwsxlTMsWQax2mMEDrCEa1B10bc_Lr2TAns1hISz_9UUf4ho_
paypal.mode=sandbox

# SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=globextunisia@gmail.com
spring.mail.password=cgcuqnrbftencakg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


logging.level.org.springframework.security=DEBUG